apiVersion: apps/v1
kind: Deployment
metadata:
  name: rms-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rms-app
  template:
    metadata:
      labels:
        app: rms-app
    spec:
      containers:
        - name: rms-container
          image: sharafynna/rms-docker-img
          ports:
            - containerPort: 5050
